# -*- coding: utf-8 -*-
"""arabic-blip2-vqa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Y59SRB_BADRdccugHZiqpIDROVJ3A28
"""

from datasets import Dataset
import requests
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from transformers import BlipProcessor, BlipForQuestionAnswering
import torch

#creating the dataset
def gen():
    yield { "qid": "0", "Image": "/media/0.jpg",
        "question": "أين التقطت هذه الصورة؟", "answer": "مدينة نيويورك" }
    yield { "qid": "1", "Image": "/media/0.jpg",
          "question": "ما هو التمثال الظاهر في الصورة؟", "answer": "تمثال الحرية" }
    yield { "qid": "2","Image": "/media/0.jpg",
        "question": "هل العيش هنا مكلف؟","answer": "نعم" }
    yield { "qid": "3", "Image": "/media/3.jpg",
            "question": "ما هذه الأداة؟", "answer": "سكين" }
    yield { "qid": "4", "Image": "/media/3.jpg",
            "question": "هل هذه الأداة خطيرة؟", "answer": "نعم" }
    yield { "qid": "5", "Image": "/media/3.jpg",
            "question": "أين يمكن شراء هذه الأداة؟", "answer": "سوبر ماركت" }
    yield { "qid": "6", "Image": "/media/6.jpg",
            "question": "أين هذا؟", "answer": "مكة، المملكة العربية السعودية" }
    yield { "qid": "7", "Image": "/media/6.jpg",
            "question": "ماذا يفعل الناس؟", "answer": "الطواف حول الكعبة" }
    yield { "qid": "8", "Image": "/media/6.jpg",
            "question": "أين هذا؟", "answer": "الكعبة المشرفة" }
    yield { "qid": "9", "Image": "/media/9.jpg",
            "question": "ما هذه اللغة؟", "answer": "اللغة العربية" }
    yield { "qid": "10", "Image": "/media/9.jpg",
            "question": "كم عدد الحروف في هذه اللغة؟", "answer": "28"}
    yield { "qid": "11", "Image": "/media/9.jpg",
            "question": "ما لون هذه الحروف؟", "answer": "أسود" }
    yield { "qid": "12", "Image": "/media/12.jpg",
            "question": "ما هذا الحيوان؟", "answer": "كلب" }
    yield { "qid": "13", "Image": "/media/12.jpg",
            "question": "هل هذا الحيوان أليف؟", "answer": "نعم" }
    yield { "qid": "14", "Image": "/media/14.jpg",
            "question": "هل ترى كلب في الصورة؟", "answer": "نعم" }
    yield { "qid": "15", "Image": "/media/14.jpg",
            "question": "هل ترى حيوان الصورة؟", "answer": "نعم" }
    yield { "qid": "16", "Image": "/media/16.jpg",
            "question": "هل ترى حيوان الصورة؟", "answer": "نعم" }
    yield { "qid": "17", "Image": "/media/16.jpg",
            "question": "ما الحيوان الظاهر في الصورة؟", "answer": "قط" }
    yield { "qid": "18", "Image": "/media/18.jpg",
            "question": "ما هذا؟", "answer": "شارع" }
    yield { "qid": "19", "Image": "/media/18.jpg",
            "question": "ما هذا؟", "answer": "طريق"}
    yield { "qid": "20", "Image": "/media/20.jpg",
            "question": "ما هذا؟", "answer": "شارع"   }
    yield { "qid": "21", "Image": "/media/20.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "إشارة مرور"   }
    yield { "qid": "22", "Image": "/media/20.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "سيارة"  }
    yield { "qid": "23", "Image": "/media/23.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "هاتف محمول"    }
    yield { "qid": "24", "Image": "/media/23.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "جوال ذكي"}
    yield { "qid": "25", "Image": "/media/25.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "هاتف محمول"    }
    yield { "qid": "26", "Image": "/media/26.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "أسلاك كهربائية"   }
    yield { "qid": "27", "Image": "/media/26.jpg",
            "question": "ما فائدة هذه الأسلاك؟", "answer": "موصلة للكهرباء"}
    yield { "qid": "28", "Image": "/media/28.jpg",
            "question": "ما فائدة هذه الأسلاك؟", "answer": "موصلة للكهرباء"  }
    yield { "qid": "29", "Image": "/media/28.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "أسلاك كهربائية"    }
    yield { "qid": "30", "Image": "/media/28.jpg",
            "question": "أين يمكن شراء هذا؟", "answer": "محل مستلزمات كهربائية"   }
    yield { "qid": "31", "Image": "/media/31.jpg",
            "question": "ما هذا؟", "answer": "بحر"    }
    yield { "qid": "32", "Image": "/media/31.jpg",
            "question": "ما هذا؟", "answer": "شاطئ"    }
    yield { "qid": "33", "Image": "/media/33.jpg",
            "question": "ما هذا؟", "answer": "بحر"  }
    yield { "qid": "34", "Image": "/media/33.jpg",
            "question": "ماذا ترى في هذه الصورة؟", "answer": "شاطئ"  }
    yield { "qid": "35", "Image": "/media/35.jpg",
            "question": "ماذا ترى في هذه الصورة؟", "answer": "باص"    }
    yield { "qid": "36", "Image": "/media/35.jpg",
            "question": "هل ترى مركبة في الصورة؟", "answer": "نعم"    }
    yield { "qid": "37", "Image": "/media/35.jpg",
            "question": "ماهو لون الباص؟", "answer": "أخضر"   }
    yield { "qid": "38", "Image": "/media/38.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "باص"    }
    yield { "qid": "39", "Image": "/media/38.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "باص"  }
    yield { "qid": "40", "Image": "/media/38.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "حافلة"    }
    yield { "qid": "41", "Image": "/media/41.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "فواكه"    }
    yield { "qid": "42", "Image": "/media/41.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "تفاح"    }
    yield { "qid": "43", "Image": "/media/41.jpg",
            "question": "هل يوجد طعام في الصورة؟", "answer": "نعم"  }
    yield { "qid": "44", "Image": "/media/44.jpg",
            "question": "هل يوجد طعام في الصورة؟", "answer": "نعم"  }
    yield { "qid": "45", "Image": "/media/44.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "فواكه"  }
    yield { "qid": "46", "Image": "/media/44.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "تفاح" }
    yield { "qid": "47", "Image": "/media/47.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "خروف"  }
    yield { "qid": "48", "Image": "/media/47.jpg",
            "question": "هل ترى حيوان في الصورة؟", "answer": "نعم"  }
    yield { "qid": "49", "Image": "/media/49.jpg",
            "question": "هل ترى حيوان في الصورة؟", "answer": "نعم" }
    yield { "qid": "50", "Image": "/media/49.jpg",
            "question": "ما هو الحيوان الظاهر في الصورة؟", "answer": "خروف"  }
    yield { "qid": "51", "Image": "/media/49.jpg",
            "question": "ما لون هذا الخروف؟", "answer": "أسود"}
    yield { "qid": "52", "Image": "/media/52.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "مظلة شمسية" }
    yield { "qid": "53", "Image": "/media/52.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "كرسي"}
    yield { "qid": "54", "Image": "/media/54.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "فتاة تحمل مظلة شمسية"}
    yield { "qid": "55", "Image": "/media/54.jpg",
            "question": "ما هو لون المظلة؟", "answer": "أبيض" }
    yield { "qid": "56", "Image": "/media/56.jpg",
            "question": "ما هو لون المظلة؟", "answer": "أحمر"  }
    yield { "qid": "57", "Image": "/media/57.jpg",
            "question": "ما هي هذه الأداة؟", "answer": "سكين" }
    yield { "qid": "58", "Image": "/media/57.jpg",
            "question": "هل هذه الأداة حادة؟", "answer": "نعم"  }
    yield { "qid": "59", "Image": "/media/59.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "طعام"}
    yield { "qid": "60", "Image": "/media/59.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "بيتزا"}
    yield { "qid": "61", "Image": "/media/61.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "بيتزا"  }
    yield { "qid": "62", "Image": "/media/62.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دراجة نارية"   }
    yield { "qid": "63", "Image": "/media/62.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "مركبة"}
    yield { "qid": "64", "Image": "/media/64.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "مركبة"  }
    yield { "qid": "65", "Image": "/media/64.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دراجة نارية"}
    yield { "qid": "66", "Image": "/media/64.jpg",
            "question": "ما هي المركبة الظاهرة في الصورة؟", "answer": "دراجة نارية"}
    yield { "qid": "67", "Image": "/media/67.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "لاعب تنس"}
    yield { "qid": "68", "Image": "/media/67.jpg",
            "question": "ما هو نوع هذه الرياضة؟", "answer": "رياضة التنس"  }
    yield { "qid": "69", "Image": "/media/69.jpg",
            "question": "ما هو نوع هذه الرياضة؟", "answer": "رياضة التنس" }
    yield { "qid": "70", "Image": "/media/69.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "لاعب تنس"}
    yield { "qid": "71", "Image": "/media/71.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "لاعب كرة قدم" }
    yield { "qid": "72", "Image": "/media/71.jpg",
            "question": "ما نوع هذه الرياضة؟", "answer": "كرة قدم"   }
    yield { "qid": "73", "Image": "/media/73.jpg",
            "question": "ما نوع هذه الرياضة؟", "answer": "كرة قدم"}
    yield { "qid": "74", "Image": "/media/73.jpg",
            "question": "ماذا يفعل الناس في الصورة؟", "answer": "يلعبون رياضة كرة القدم"}
    yield { "qid": "75", "Image": "/media/75.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دمية"  }
    yield { "qid": "76", "Image": "/media/75.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دمية دب قطنية"}
    yield { "qid": "77", "Image": "/media/77.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دمية دب قطنية"  }
    yield { "qid": "78", "Image": "/media/77.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "دمية"}
    yield { "qid": "79", "Image": "/media/77.jpg",
            "question": "ما هذا الحيوان؟", "answer": "دب"}
    yield { "qid": "80", "Image": "/media/80.jpg",
            "question": "ما هذا الحيوان؟", "answer": "زرافة"}
    yield { "qid": "81", "Image": "/media/80.jpg",
            "question": "هل ترى حيوان في الصورة؟", "answer": "نعم" }
    yield { "qid": "82", "Image": "/media/80.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "زرافة"}
    yield { "qid": "83", "Image": "/media/83.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "زرافة"}
    yield { "qid": "84", "Image": "/media/83.jpg",
            "question": "هل ترى حيوان في الصورة؟", "answer": "نعم"}
    yield { "qid": "85", "Image": "/media/85.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "طائر"  }
    yield { "qid": "86", "Image": "/media/85.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "كتاب"}
    yield { "qid": "87", "Image": "/media/87.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "مجموعة من الكتب"}
    yield { "qid": "88", "Image": "/media/87.jpg",
            "question": "هل ترى كتاب؟", "answer": "نعم"}
    yield { "qid": "89", "Image": "/media/89.jpg",
            "question": "ماذا يوجد في الصورة؟", "answer": "ساعة"}
    yield { "qid": "90", "Image": "/media/89.jpg",
            "question": "ماذا يوجد في الصورة؟", "answer": "ساعة معلقة على مبنى"  }
    yield { "qid": "91", "Image": "/media/91.jpg",
            "question": "ماذا يوجد في الصورة؟", "answer": "ساعة معلقة على مبنى"   }
    yield { "qid": "92", "Image": "/media/91.jpg",
            "question": "هل ترى ساعة في الصورة؟", "answer": "نعم" }
    yield { "qid": "93", "Image": "/media/93.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "حاسب آلي"}
    yield { "qid": "94", "Image": "/media/93.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "جهاز حاسب محمول"}
    yield { "qid": "95", "Image": "/media/95.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "جهاز حاسب محمول"  }
    yield { "qid": "96", "Image": "/media/95.jpg",
            "question": "ماذا ترى في الصورة؟", "answer": "حاسب آلي"  }
    yield { "qid": "97", "Image": "/media/95.jpg",
            "question": "هل ترى حاسب آلي في الصورة؟", "answer": "نعم"}
    yield { "qid": "98", "Image": "/media/98.jpg",
            "question": "هل ترى حاسب آلي في الصورة؟", "answer": "نعم" }
    yield { "qid": "99", "Image": "/media/98.jpg",
            "question": "ماذا يفعلون الأشخاص في الصورة؟", "answer": "العمل على أجهزة الحاسوب الآلي"   }

ds = Dataset.from_generator(gen)

#VQA dataset class
class VQADataset(Dataset):
    def __init__(self, dataset, processor):
        self.dataset = dataset
        self.processor = processor

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        item = self.dataset[idx]
        image= Image.open(item["Image"]).convert('RGB')
        encoding = self.processor(images=image, texts=item["question"], padding="max_length", return_tensors="pt")
        labels = self.processor(text = item['answer'], padding = "max_length", return_tensors = "pt").input_ids

        encoding['labels'] = labels
        # remove batch dimension
        encoding = {k:v.squeeze() for k,v in encoding.items()}

        return encoding

#importing the model
processor = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")

#preparing the dataset
train_dataset = VQADataset(ds, processor)
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=2)

#training section
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

model.train()

for epoch in range(50):
  print("Epoch:", epoch)
  for idx, batch in enumerate(train_dataloader):
    pixel_values = batch["pixel_values"].to(device)
    input_ids = batch["labels"].to(device)


    outputs = model(input_ids=input_ids,
                    pixel_values=pixel_values,
                    labels=input_ids)

    loss = outputs.loss

    print("Loss:", loss.item())

    loss.backward()

    optimizer.step()
    optimizer.zero_grad()


#using the model
img_url = 'ENTER IMAGE PATH'
raw_image = Image.open(img_url).convert('RGB')

question = "ENTER QUESTION"
inputs = processor(raw_image, question, return_tensors="pt")

inputs.to(device)

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))